### ISSUE TITLE
404 job.yml

### ISSUE THREAD

**Issue by andrealmar** [lwolf/kube-cleanup-operator#17]
The example job is giving me 404: 

https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml

**Comment by lwolf** [comment]
Thanks for letting me know. 
urls have changed in k8s docs. this should work
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/controllers/job.yaml

**Comment by andrealmar** [comment]
You're welcome. You can also use this one: https://k8s.io/examples/controllers/job.yaml

**Comment by lwolf** [comment]
this one should be permanent. thanks
