### ISSUE TITLE
Allow delay in job cleanup

### ISSUE THREAD

**Issue by fuel-wlightning** [lwolf/kube-cleanup-operator#2]
As it stands, the job gets cleaned up immediately upon completion. 

I would like to place a configurable delay on this, for instance 10 minute delay would allow a script watching for job completion to see it's job complete. A 1 hour delay might allow a manually initiated job to be seen by the issuer.

**Comment by lwolf** [comment]
That makes sense.
I was thinking about adding some options `like` delay and `do-not-delete` using annotations inside jobs.

**Comment by aalubin** [comment]
Added a pull request with number of days to keep failed/successful jobs

**Comment by fuel-wlightning** [comment]
PR #7 for relation purposes

**Comment by lwolf** [comment]
merged now
