### ISSUE TITLE
Resource requests and limits should be defined in the deployment manifest

### ISSUE THREAD

**Issue by gtseres** [lwolf/kube-cleanup-operator#23]
The Kubernetes scheduler will be able to make better decisions on scheduling the `kube-cleanup-operator` if resource requests and limits were defined for CPU and memory. This needs to be done in the [`deployment.yaml`](https://github.com/lwolf/kube-cleanup-operator/blob/master/deploy/deployment.yaml). I would be happy to add those if you could provide some intuition around how many resources the operator needs.

**Comment by lwolf** [comment]
Thanks, for your interest in cleanup-operator.
I originally put those deploy scripts as an example. 
Resource usage, at least CPU, could vary based on the hardware, but in my cluster I usually see values like this: memory ~20mb, cpu ~almost zero.

Please feel free to create a PR with resource allocations.

**Comment by gtseres-workable** [comment]
Thanks for the feedback! How much does the utilisation spike when there are many jobs to cleanup?

**Comment by gtseres** [comment]
Thanks for the feedback! How much does the utilisation spike when there are many jobs to cleanup?

**Comment by lwolf** [comment]
Unfortunately, I don't have historical data available.
I would say, lets set it to something like 50mb of ram and 0.01 cpu, as a default. 
People can always adjust it if needed
