### ISSUE TITLE
kube-cleanup-operator does not work on GKE

### ISSUE THREAD

**Issue by gtseres** [lwolf/kube-cleanup-operator#24]
I followed the steps in the readme file, but faced an issue when running the binary:

```shell
make install_deps
make build
./bin/kube-cleanup-operator --help --> successful
./bin/kube-cleanup-operator --run-outside-cluster --namespace=default -dry-run --> error
```

The error is the following:
```
panic: No Auth Provider found for name "gcp"

goroutine 1 [running]:
main.main()
	/Users/george/go/src/github.com/lwolf/kube-cleanup-operator/cmd/main.go:42 +0x8e2
```

I have managed to overcome this issue by replacing the following line in [main.go](https://github.com/lwolf/kube-cleanup-operator/blob/master/cmd/main.go):

`_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"`

to

`_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"`

Am I doing something wrong?

**Comment by gtseres** [comment]
Maybe adding line `_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"` can help fix the issue. Can you please verify if the suggested fix is valid so that I can send out a PR? Thanks!

**Comment by lwolf** [comment]
I guess something changed auth module. I don't have GCP cluster to test.
Could you try replacing 
```
_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
```
with
``` 
_  "k8s.io/client-go/plugin/pkg/client/auth

```
This should include all possible auth providers and fix the issue.

**Comment by gtseres** [comment]
Thanks for the feedback. I tried that out and run
```
make install_deps
make build
```

but I got the following:

```
--> Go Version
go version go1.11.2 darwin/amd64
--> Compiling the project
go build -ldflags "-X main.gitsha=v0.1-22-g86418f1-dirty -X main.compiled=1550601150" -o bin/kube-cleanup-operator ./cmd
# github.com/lwolf/kube-cleanup-operator/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:241:4: cannot use expiresIn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:242:4: cannot use expiresOn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:243:4: cannot use expiresOn (type string) as type json.Number in field value
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:260:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:261:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:295:3: cannot use spt.Token (type func() adal.Token) as type adal.Token in field value
make: *** [build] Error 2
```

**Comment by lwolf** [comment]
that's weird, ok, thanks for trying.
let's just have 2 auth modes imported for now, as a workaround.
I'll look at it later

```
_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

**Comment by gtseres** [comment]
I have sent out this PR, please let me know if any comments: https://github.com/lwolf/kube-cleanup-operator/pull/26

**Comment by lwolf** [comment]
I cut the release with all your changes.
https://github.com/lwolf/kube-cleanup-operator/releases/tag/v0.4.4

Thank you for your contributions.
