### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by Laxman-SM** [lwolf/kube-cleanup-operator#3]
MacBook-Pro:kube-cleanup-operator itru$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml
error: error validating "https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml": error validating data: found invalid field backoffLimit for v1.JobSpec; if you choose to ignore these errors, turn validation off with --validate=false

after turning off this creating job successfully
kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml --validate=false
job "pi" created

**Comment by Laxman-SM** [comment]
Also remove kubectl create that mentioned twice in below command.

presents 
# Use simple job to test it
kubectl create -f kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml

After 
kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml

**Comment by lwolf** [comment]
1. what version of k8s are you using? 
2. thanks for noticing

**Comment by Laxman-SM** [comment]
HI,

i am using 1.7.5 version.

**Comment by lwolf** [comment]
`.spec.backoffLimit` was added only in 1.8
Could you try to fetch that failing manifest, remove this field and try again?

**Comment by lwolf** [comment]
do you still have a problem with it?

**Comment by Laxman-SM** [comment]
Hi,


Sorry for delayed reply i will check  and let you if in few days.

________________________________

**Comment by Laxman-SM** [comment]
Hi,


That working fine after removal of mentioned field.



________________________________

**Comment by lwolf** [comment]
great, closing now
