### ISSUE TITLE
Does not remove jobs/pods that were created before Cleanup Operator was running 

### ISSUE THREAD

**Issue by gkrizek** [lwolf/kube-cleanup-operator#32]
I have clusters with lots of completed jobs across several namespaces. When I run the cleanup-operator, I expected it to remove the old jobs that were already on the cluster. Instead it doesn't and only removes jobs that were ran and finished _after_ cleanup-operator was running. 

Is this expected behavior?

**Comment by lwolf** [comment]
Yes it was initially designed this way. 
But it makes sense to add an configuration option to cleanup old pods as well.
thanks

**Comment by gkrizek** [comment]
Ok, thanks for clarifying.
