### ISSUE TITLE
Requested memory for deployment manifest is not high enough for large clusters

### ISSUE THREAD

**Issue by cheeseandcereal** [lwolf/kube-cleanup-operator#34]
When running this deployment with the given manifest (https://github.com/lwolf/kube-cleanup-operator/blob/master/deploy/deployment.yaml) on larger clusters, this runs out of memory:

```
State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```

My cluster that this failed on had ~3500 pods.

Bumping up to `100Mi` seemed to work for me.

I'd recommend either changing the manifest, or leaving a comment by the resources that mentions the memory limit should be bumped up on larger clusters.

**Comment by lwolf** [comment]
Deployment files in the repo are for demonstration purposes and should be customized for specific use cases.
