### ISSUE TITLE
Expose cleanup Operator Metrics /metrics to be monitored by prometheus

### ISSUE THREAD

**Issue by bahaeddine** [lwolf/kube-cleanup-operator#42]
To be able to monitor Cleanup Operator by Prometheus, we need to expose its metrics.

**Comment by lwolf** [comment]
any specific metrics you're interested in?

**Comment by lwolf** [comment]
Basic metrics are now available in 0.7 release.
https://github.com/lwolf/kube-cleanup-operator/releases/tag/v0.7.0

**Comment by bahaeddine** [comment]
Thank you for your feedback and your support. I will try these metrics and update you if there are a some missing.
