### ISSUE TITLE
Keep parameters in minutes

### ISSUE THREAD

**Issue by keszi000** [lwolf/kube-cleanup-operator#44]
invalid value "0.1" for flag -keep-successful: parse error
invalid value "0,1" for flag -keep-successful: parse error

I need these jobs for only ~10 minutes. Is it possible?

**Comment by lwolf** [comment]
Only integer values (as number of hours) are currently supported.
Could you share your usecase please?

**Comment by lwolf** [comment]
Hi, this should be possible with the latest 0.7 release, could you give it a try?
https://github.com/lwolf/kube-cleanup-operator/releases/tag/v0.7.0

Make sure to run it with `-legacy-mode=false` to be able to use arguments.

**Comment by keszi000** [comment]
Sorry for the passivity.
This is awesome! You are the best!
