### ISSUE TITLE
RBAC issue

### ISSUE THREAD

**Issue by keszi000** [lwolf/kube-cleanup-operator#46]
E0529 09:40:00.113780       1 reflector.go:178] github.com/lwolf/kube-cleanup-operator/pkg/controller/controller.go:143: Failed to list *v1.Job: jobs.batch is forbidden: User "system:serviceaccount:default:cleanup-operator" cannot list resource "jobs" in API group "batch" at the cluster scope

pls fix it in the deployment RBAC file:
`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: ["batch", "extensions"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - delete
`

**Comment by lwolf** [comment]
should work now
