### ISSUE TITLE
Pending pods don't get cleaned up

### ISSUE THREAD

**Issue by patrungel** [lwolf/kube-cleanup-operator#51]
Pods in the pending state get never cleaned up.

How to reproduce:
1. Configure kube-cleanup-operator to clean up pending pods:
```
...
-delete-pending-pods-after=3m
...
```

2. Launch a pod that will never get scheduled (tested with a job and with a standalone pod).
For instance:
```
...
nodeSelector:
  feature: dummy
...
```
3. Wait until the retention is due.

Expected: the pending pod is deleted
Actual result: the pod is not deleted

Current configuration as logged:
```
2020/06/23 16:12:31 Provided options: 
	namespace: test-cleanup
	dry-run: false
	delete-successful-after: 3m0s
	delete-failed-after: 3m0s
	delete-pending-after: 3m0s
	delete-orphaned-after: 3m0s
	delete-evicted-after: 3m0s

	legacy-mode: false
	keep-successful: 0
	keep-failures: -1
	keep-pending: -1

```

**Comment by lwolf** [comment]
what's the k8s version?

**Comment by patrungel** [comment]
1.15

**Comment by shelbaz** [comment]
Im on k8s 1.16 and it doesnt seem to be cleaning anything outside of the default namespace. I set it up out of the box using the instructions. 
![image](https://user-images.githubusercontent.com/18130581/85894420-b8315280-b7c2-11ea-82e0-9b2da3285a90.png)

**Comment by sorinjulean** [comment]
Can be reproduced for version 1.18.4

**Comment by lwolf** [comment]
Yeah, thanks, working on a fix
