### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by dududko** [lwolf/kube-cleanup-operator#60]
Is there the official helm chart for this operator ?

**Comment by lwolf** [comment]
No, the chart felt like overkill for this simple thing.
Do you think it needs one?

**Comment by dududko** [comment]
@lwolf 
I believe it is good to pack it into a helm chart. 
Even with the small project like this, it would be very convenient to have a helm chart with a specified version and the list of configurable parameters. It will also be easier to rollout changes if the list of kubernetes objects will change (for example if you will decide to use a statefulset instead of deployment). Also by making a helm chart and by uploading it to the helm hub the `kube-cleanup-operator` project will attract more users/contributors.

**Comment by lwolf** [comment]
Thanks for the suggestion, I'll keep it in mind for the next release.

**Comment by qbasicer** [comment]
+1 for a helm chart specifically to parameterize the namespace config

**Comment by haarchri** [comment]
added a helm chart for kube-cleanup-operator - please have a look if its fits ;)

**Comment by lwolf** [comment]
thanks for the PR, will take a look over weekend

**Comment by lwolf** [comment]
Thanks @haarchri.
PR is merged, I'll close the issue after I publish it to the registry.

**Comment by pranas** [comment]
looking forward to the Helm chart

**Comment by lwolf** [comment]
Chart is published to https://charts.lwolf.org/ (https://github.com/lwolf/kube-charts)

```
$ helm repo add lwolf-charts http://charts.lwolf.org
"lwolf-charts" has been added to your repositories
$ helm search kube-cleanup
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
lwolf-charts/kube-cleanup-operator	1.0.0        	v0.8.1     	Kubernetes Operator to automatically delete completed Job...
```
