### ISSUE TITLE
be able to specify different successful/failed ttl for each pod/job

### ISSUE THREAD

**Issue by dududko** [lwolf/kube-cleanup-operator#62]
Instead of using the global ttl configured in cleanup-operator, I would like to specify ttl more granual. Say, using the labels or annotations set ttl=1h on successful completion for job A, and specify ttl=10m for failed completion for job B.

I would like to do this using the labels `kube-cleanup-operator/ttl-success: 1h` and `kube-cleanup-operator/ttl-fail: 10m`.

Why is it important ?
For some releases it is very important to read and analyze logs before removing pods or jobs, but for other is it not so important. This is why in many cases you need to specify different ttl for each job, or use the default value from the cleanup-operator.

**Comment by lwolf** [comment]
Using annotations for this fine-tuning was the plan from the beginning, but nobody asked for it, so I kept it simple.
I'll look into the implications of adding it, when I have cycles to work on it.

Thanks

**Comment by lwolf** [comment]
closing this in favor of https://github.com/lwolf/kube-cleanup-operator/issues/72
