### ISSUE TITLE
ignore namespaces

### ISSUE THREAD

**Issue by rpatel-repay** [lwolf/kube-cleanup-operator#69]
i would like the ability to ignore namespaces rather than limiting the scope to certain namespace.  Also to be able to take in a list as well, there could be many teams that do not want the jobs touched and this would be a value add.

**Comment by lwolf** [comment]
Currently, you can either specify one namespace or run it cluster-wide without restrictions.

If cluster-wide deployment doesn't work for your use case, you can deploy one instance per namespace that you need to monitor.

**Comment by rpatel-repay** [comment]
okay thanks, running many instance of this in different namespaces would cause more maintenance overhead as we would have this in every overlay for each team rather than a central location to control.
