### ISSUE TITLE
Problems running helm

### ISSUE THREAD

**Issue by montgomery-auber** [lwolf/kube-cleanup-operator#80]
Hi,
I am  a bit confused, so the issue might be above the keyboard. I do need the namespace support so would like to use the helm cleanup operator. It runs great with kubectl apply with the rbac and deployment yaml files.
But when I install the helm chart from the helm repo with  "helm install  cleanup lwolf-charts/kube-cleanup-operator"
I get:
`W1102 05:21:49.379093       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021/11/02 05:21:49 Controller started...
2021/11/02 05:21:49 Listening at 0.0.0.0:7000
2021/11/02 05:21:49 Listening for changes...
E1102 05:21:49.588274       1 reflector.go:178] github.com/lwolf/kube-cleanup-operator/pkg/controller/controller_legacy.go:135: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:cleanup-kube-cleanup-operator" cannot list resource "pods" in API group "" at the cluster scope`

I ALSO tried helm install  from cloned git repo, then the error is  "1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 node(s) didn't match Pod's node affinity/selector."  same happened even if I added affinity to the node tags.

Thanks

**Comment by lwolf** [comment]
Hi
```
Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:cleanup-kube-cleanup-operator" cannot list resource "pods" in API group "" at the cluster scope
```

says that RBAC wasn't applied
