### ISSUE TITLE
helmchart not work

### ISSUE THREAD

**Issue by refaelb** [lwolf/kube-cleanup-operator#81]
E1227 08:28:34.712122       1 reflector.go:178] pkg/controller/controller.go:154: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:cleanup-operator" cannot list resource "pods" in API group "" in the namespace "default"

**Comment by lwolf** [comment]
You haven't deployed rbac policies

**Comment by refaelb** [comment]
yes . its work for all namespaces but for 1 namespace its not work & this its problem ..
