### ISSUE TITLE
Need support for priorityClass and containerSecurityContext

### ISSUE THREAD

**Issue by AshutoshNirkhe** [lwolf/kube-cleanup-operator#83]
The kube-cleanup-operator chart shall support providing container level securityContext and priorityClass for the pod. <br>
I can raise a PR for this if you are good @lwolf :)

**Comment by lwolf** [comment]
Sure, feel free to make a PR

**Comment by AshutoshNirkhe** [comment]
> Sure, feel free to make a PR

Opened https://github.com/lwolf/kube-cleanup-operator/pull/84 . Please feel free to review/approve if good. Thanks.
