### ISSUE TITLE
Pulling from helm chart kube-cleanup-operator-1.0.3.tgz file not found

### ISSUE THREAD

**Issue by ankita-hubjoin** [lwolf/kube-cleanup-operator#85]
We are getting error "Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: failed to fetch http://charts.lwolf.org/kube-cleanup-operator-1.0.3.tgz : 404 Not Found". When we check in the helm search repo kube-cleanup its exist (attached images). While running pulumi preview we are getting error (attached images).
Could you please look into this issue.
 
![image](https://user-images.githubusercontent.com/71072631/159739272-80a65720-9ab0-4453-9ffc-6d31c9023293.png)

![image](https://user-images.githubusercontent.com/71072631/159738842-91ba6618-61e4-4960-b543-313981e4da02.png)

Thanks,
Ankita

**Comment by lwolf** [comment]
Thanks.
Pushed the missing tar. Could you update the repo index and try again (might take 5-10 minutes to update cache)

**Comment by ankita-hubjoin** [comment]
Thankyou for your quick response.
