### ISSUE TITLE
Remove restartCount check

### ISSUE THREAD

**Issue by aalubin** [lwolf/kube-cleanup-operator#9]
Hi,
Currently pods with restart count > 0 will not be handled.

I have few issues with this check:
1. It is only for the first container in the pod, but this can be easily checked.
2. I am not sure restart count is relevant, now that you can keep success/failed pods/jobs
3. As is, it causes index out of range when a new job is added and container was not started yet.

So I suggest to remove this check.

**Comment by lwolf** [comment]
I agree, with the new keep success/failed we can get rid of this check.

**Comment by aalubin** [comment]
OK I will PR both this and an updated maven file later on today

**Comment by lwolf** [comment]
awesome, thanks.

I believe you meant makefile, not maven :)

**Comment by aalubin** [comment]
Yeap 
Doing some maven changes@work in parallel
:)

**Comment by aalubin** [comment]
#10

**Comment by aalubin** [comment]
@lwolf you can now run docker-release if you have quay.io permission. further work needs to be done to the travis file so it will push automatically with every commit

**Comment by lwolf** [comment]
@aalubin I have just released it manually to both docker and quay.io. works great.
